/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DNAnalyzer;

import org.junit.jupiter.api.Test;

public class MainTest {
	@Test
	public void mainClassshouldExist() throws ClassNotFoundException {
		Class.forName("DNAnalyzer.Main");
	}
}
