/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DNAnalyzer;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    @Test public void mainClassshouldExist() throws ClassNotFoundException {
        Class.forName("DNAnalyzer.Main");
    }
}
