/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dnanalyzer;

public class MainTest {
    // @Test
    public void mainClassshouldExist() throws ClassNotFoundException {
        Class.forName("DNAnalyzer.Main");
    }
}
