package DNAnalyzer

enum class AminoAcidNames {
    ISOLEUCINE, LEUCINE, VALINE, PHENYLALANINE, METHIONINE, CYSTEINE, ALANINE, GLYCINE, PROLINE, THREONINE, SERINE, TYROSINE, TRYPTOPHAN, GLUTAMINE, ASPARAGINE, HISTIDINE, GLUTAMIC_ACID, ASPARTIC_ACID, LYSINE, ARGININE, STOP
}